name: Node CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: vef2test
        ports:
          - 5432:5432
        # Bíður eftir að gagnagrunnur sé klár:
        options: >-
          --health-cmd="pg_isready -U test" 
          --health-interval=5s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Set up database URL
        run: echo "DATABASE_URL=postgresql://test:test@localhost:5432/vef2test" >> $GITHUB_ENV

      - name: Run migrations
        run: npx prisma migrate deploy

      - name: Run tests
        run: npm test
